# theme: jekyll-theme-cayman
# theme: jekyll-theme-minimal
# theme: jekyll-theme-leap-day
# jekyll-theme-hacker
# jekyll-theme-midnight
# jekyll-theme-primer
# jekyll-theme-merlot
# jekyll-theme-slate
# jekyll-theme-tactile
# jekyll-theme-time-machine

title: "GitHub Page of Gábor Szabó"
show_downloads: false
plugins:
  - jekyll-remote-theme

# theme: beautiful-jekyll  # Theme not found (this is fine, it is a remote theme)

# remote_theme: mmistakes/minimal-mistakes     # Unknown tag 'include_cached'
# remote_theme: "chirpy-dev/chirpy"            # not found
remote_theme: "just-the-docs/just-the-docs"  # Error: File to import not found or unreadable: just-the-docs.
# remote_theme: "daattali/beautiful-jekyll"
# remote_theme: "mmistakes/so-simple-theme"
